FROM node:14.16-alpine

WORKDIR /usr/src/app

RUN yarn global add json-server

EXPOSE ${APICONFIG_PORT}

CMD ["json-server", "/config/api-config-server.json", "--routes", "/config/routes.json", "--host", "0.0.0.0"]
