openapi: 3.0.0
info:
  version: 0.1.0
  title: Pagopa eCommerce payment methods service
  description: This microservice handles payment methods.
paths:
  /payment-methods:
    post:
      operationId: newPaymentMethod
      summary: Make a new payment method
      requestBody:
        $ref: "#/components/requestBodies/PaymentMethodRequest"
      responses:
        '200':
          description: New payment method successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentMethodResponse'
    get:
      operationId: getAllPaymentMethods
      summary: Retrieve all Payment Methods (by filter)
      parameters:
        - name: amount
          in: query
          description: Payment Amount
          required: false
          schema:
            type: number
      responses:
        '200':
          description: Payment method successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaymentMethodResponse'
  /payment-methods/{id}:
    patch:
      operationId: patchPaymentMethod
      summary: Update payment method
      parameters:
        - name: id
          in: path
          description: Payment Method ID
          required: true
          schema:
            type: string
      requestBody:
        $ref: "#/components/requestBodies/PatchPaymentMethodRequest"
      responses:
        '200':
          description: Payment method successfully retrived
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentMethodResponse'
    get:
      operationId: getPaymentMethod
      summary: Retrive payment method by ID
      parameters:
        - name: id
          in: path
          description: Payment Method ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: New payment method successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentMethodResponse'
  /payment-methods/psps:
    put:
      operationId: scheduleUpdatePSPs
      summary: Update psp list
      responses:
        '200':
          description: Update successfully scheduled
    get:
      operationId: getPSPs
      summary: Retrieve psps
      parameters:
        - in: query
          name: amount
          schema:
            type: integer
          description: Amount in cents
          required: false
        - in: query
          name: lang
          schema:
            type: string
            enum: [IT, EN, FR, DE, SL]
          description: Service language
          required: false
        - in: query
          name: paymentTypeCode
          schema:
            type: string
          description: Payment Type Code
          required: false
      responses:
        '200':
          description: PSP list successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PSPsResponse'

  /payment-methods/{id}/psps:
    get:
      operationId: getPaymentMethodsPSPs
      summary: Retrive PSPs by payment method ID
      parameters:
        - name: id
          in: path
          description: Payment Method ID
          required: true
          schema:
            type: string
        - in: query
          name: amount
          schema:
            type: integer
          description: Amount in cents
          required: false
        - in: query
          name: lang
          schema:
            type: string
            enum: [IT, EN, FR, DE, SL]
          description: Service language
          required: false
      responses:
        '200':
          description: New payment method successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PSPsResponse'
components:
  schemas:
    PaymentMethodRequest:
      type: object
      description: New Payment method Request
      properties:
        name:
          type: string
        description:
          type: string
        asset:
          type: string
        status:
          type: string
          enum: ["ENABLED","DISABLED","INCOMING"]
        paymentTypeCode:
          type: string
        ranges:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/Range"
      required:
        - name
        - description
        - status
        - paymentTypeCode
        - ranges
    Range:
      type: object
      description: Payment amount range in cents
      properties:
        min:
          type: integer
          format: int64
          minimum: 0
        max:
          type: integer
          format: int64
          minimum: 0
    PatchPaymentMethodRequest:
      type: object
      description: Patch Payment Method Request
      properties:
        status:
          type: string
          enum: ["ENABLED","DISABLED","INCOMING"]
      required:
        - status
    PaymentMethodResponse:
      type: object
      description: Payment method Response
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        asset:
          type: string
        status:
          type: string
          enum: ["ENABLED","DISABLED","INCOMING"]
        paymentTypeCode:
          type: string
        ranges:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/Range"
      required:
        - id
        - name
        - description
        - status
        - paymentTypeCode
        - ranges
    PSPsResponse:
      type: object
      description: Get available PSP list Response
      properties:
        psp:
          type: array
          items:
            $ref: "#/components/schemas/Psp"
    Psp:
      type: object
      description: PSP object
      properties:
        code:
          type: string
        paymentTypeCode:
          type: string
        channelCode:
          type: string
        description:
          type: string
        status:
          type: string
          enum: ["ENABLED","DISABLED","INCOMING"]
        businessName:
          type: string
        brokerName:
          type: string
        language:
          type: string
          enum:
            - IT
            - EN
            - FR
            - DE
            - SL
        minAmount:
          type: integer
          format: int64
        maxAmount:
          type: integer
          format: int64
        fixedCost:
          type: integer
          format: int64
      required:
        - code
        - paymentMethodID
        - description
        - status
        - type
        - name
        - brokerName
        - language
        - minAmount
        - maxAmount
        - fixedCost
  requestBodies:
    PaymentMethodRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PaymentMethodRequest"
    PatchPaymentMethodRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PatchPaymentMethodRequest"