FROM node:14.17-alpine@sha256:8c94a0291133e16b92be5c667e0bc35930940dfa7be544fb142e25f8e4510a45

WORKDIR /usr/src/app

RUN yarn global add json-server

EXPOSE 8085

CMD ["json-server", "/config/api-config-server.json", "--routes", "/config/routes.json", "--middlewares", "/config/middleware.js", "--host", "0.0.0.0"]
