FROM node:18.17-alpine@sha256:3482a20c97e401b56ac50ba8920cc7b5b2022bfc6aa7d4e4c231755770cf892f

WORKDIR /usr/src/app

RUN yarn global add json-server

EXPOSE 8085

CMD ["json-server", "/config/api-config-server.json", "--routes", "/config/routes.json", "--middlewares", "/config/middleware.js", "--host", "0.0.0.0"]
