FROM node:14.17-alpine

WORKDIR /usr/src/app

RUN yarn global add json-server

EXPOSE 8085

CMD ["json-server", "/config/api-config-server.json", "--routes", "/config/routes.json", "--middlewares", "/config/middleware.js", "--host", "0.0.0.0"]
