apiVersion: v2
name: pagopa-ecommerce-payment-methods-service
description: Microservice to handle payment methods in ecommerce pagoPA
type: application
version: 0.0.6
appVersion: 0.0.6
dependencies:
  - name: microservice-chart
    version: 1.21.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
