apiVersion: v2
name: pagopa-ecommerce-payment-methods-service
description: Microservice to handle payment methods in ecommerce pagoPA
type: application
version: 0.12.1
appVersion: 0.12.1
dependencies:
  - name: microservice-chart
    version: 2.3.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
