apiVersion: v2
name: pagopa-ecommerce-payment-methods-service
description: Microservice to handle payment methods in ecommerce pagoPA
type: application
version: 3.2.2
appVersion: 3.2.2
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
