microservice-chart:
  namespace: "ecommerce"
  nameOverride: ""
  fullnameOverride: ""
  canaryDelivery:
    create: false
    ingress:
      bluegreen: false
      #set canary deployment with traffic balancing see https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#canary for more info
      header: true
      headerName: deployment
      headerValue: blue
      weightPercent: 0
    image:
      repository: pagopapcommonacr.azurecr.io/pagopaecommercepaymentmethodsservice
      tag: "latest"
    envConfig:
      OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-ecommerce-payment-methods-service-blue,deployment.environment=prod"
      ECS_SERVICE_NAME: pagopa-ecommerce-payment-methods-service-blue
    envSecret: {}
  image:
    repository: pagopapcommonacr.azurecr.io/pagopaecommercepaymentmethodsservice
    tag: "3.2.2"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 80
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 80
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
    replicas: 5
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuprod.ecommerce.internal.platform.pagopa.it"
    path: /pagopa-ecommerce-payment-methods-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: "ecommerce-workload-identity"
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "600m"
  autoscaling:
    enable: true
    minReplica: 5
    maxReplica: 10
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  terminationGracePeriodSeconds: 30
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  envConfig:
    MONGO_HOST: pagopa-p-weu-ecommerce-cosmos-account.mongo.cosmos.azure.com
    MONGO_USERNAME: pagopa-p-weu-ecommerce-cosmos-account
    MONGO_PORT: "10255"
    MONGO_SSL_ENABLED: "true"
    MONGO_MIN_POOL_SIZE: "0"
    MONGO_MAX_POOL_SIZE: "50"
    MONGO_MAX_IDLE_TIMEOUT_MS: "600000"
    MONGO_CONNECTION_TIMEOUT_MS: "2000"
    MONGO_SOCKET_TIMEOUT_MS: "10000"
    MONGO_SERVER_SELECTION_TIMEOUT_MS: "2000"
    MONGO_WAITING_QUEUE_MS: "2000"
    MONGO_HEARTBEAT_FREQUENCY_MS: "5000"
    REDIS_PORT: "6380"
    REDIS_SSL_ENABLED: "true"
    AFM_URI: "https://api.platform.pagopa.it/afm/calculator-service/v1/fees"
    AFM_URI_V2: "https://api.platform.pagopa.it/afm/calculator-service/v2/fees"
    AFM_READ_TIMEOUT: "10000"
    AFM_CONNECTION_TIMEOUT: "10000"
    SPRING_MAX_IN_MEM_SIZE: "16777216"
    OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-ecommerce-payment-methods-service,deployment.environment=prod"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    ECS_SERVICE_NAME: pagopa-ecommerce-payment-methods-service
    ECS_SERVICE_ENVIRONMENT: prod
    NPG_URI: "https://xpay.nexigroup.com/api/phoenix-0.0"
    NPG_READ_TIMEOUT: "10000"
    NPG_CONNECTION_TIMEOUT: "10000"
    SESSION_URL_BASEPATH: "https://checkout.pagopa.it"
    SESSION_URL_OUTCOME_SUFFIX: "/esito"
    SESSION_URL_CANCEL_SUFFIX: "/esito"
    SESSION_URL_NOTIFICATION_URL: "https://api.platform.pagopa.it/ecommerce/npg/notifications/v1/sessions/{orderId}/outcomes?sessionToken={sessionToken}"
    SESSION_URL_IO_PREFIX_PATH: "/ecommerce-fe"
    NPG_SESSIONS_TTL: "900"
    NPG_NOTIFICATION_JWT_VALIDITY_TIME: "900"
    SERVICE_LOGGING_LEVEL: "info"
    ROOT_LOGGING_LEVEL: "info"
    WARMUP_PAYMENT_METHOD_ID: "83b5e0c7-2d35-44f4-9e48-a168b84433a1"
    NPG_SO_KEEPALIVE: "true"
    NPG_TCP_KEEPIDLE: "30"
    NPG_TCP_KEEPINTVL: "10"
    NPG_TCP_KEEPCNT: "5"
    JWT_ISSUER_URI: "https://weuprod.ecommerce.internal.platform.pagopa.it/pagopa-jwt-issuer-service"
    JWT_ISSUER_READ_TIMEOUT: "10000"
    JWT_ISSUER_CONNECTION_TIMEOUT: "10000"
    SECURITY_API_KEY_SECURED_PATHS: "/payment-methods,/v2/payment-methods"
  envSecret:
    MONGO_PASSWORD: mongo-ecommerce-password
    REDIS_PASSWORD: redis-ecommerce-access-key
    REDIS_HOST: redis-ecommerce-hostname
    AFM_KEY: afm-api-key
    OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
    NPG_API_KEY: npg-api-key
    JWT_ISSUER_API_KEY: ecommerce-jwt-issuer-service-active-api-key
    SECURITY_API_KEY_PRIMARY: ecommerce-payment-methods-primary-api-key
    SECURITY_API_KEY_SECONDARY: ecommerce-payment-methods-secondary-api-key
  keyvault:
    name: "pagopa-p-ecommerce-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: pagopaecommercepaymentmethodsservice
            namespaces: ["ecommerce"]
            topologyKey: topology.kubernetes.io/zone
  azure:
    workloadIdentityClientId: "d5614882-90dd-47a1-aad1-cdf295201469"
