microservice-chart:
  namespace: "ecommerce"
  nameOverride: ""
  fullnameOverride: ""
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: bluegreen
    service:
      create: true
    deployment:
      create: true
      image:
        repository: pagopaucommonacr.azurecr.io/pagopaecommercepaymentmethodsservice
        tag: "latest"
        pullPolicy: Always
  envConfig:
    MONGO_HOST: pagopa-u-weu-ecommerce-cosmos-account.mongo.cosmos.azure.com
    MONGO_USERNAME: pagopa-u-weu-ecommerce-cosmos-account
    MONGO_PORT: "10255"
    MONGO_SSL_ENABLED: "true"
    AFM_URI: "https://api.dev.platform.pagopa.it/afm/calculator-service/v1/fees"
    AFM_READ_TIMEOUT: "10000"
    AFM_CONNECTION_TIMEOUT: "10000"
    SPRING_MAX_IN_MEM_SIZE: "16777216"
  envSecret:
    MONGO_PASSWORD: mongo-ecommerce-password
    AFM_KEY: afm-api-key
    APPLICATIONINSIGHTS_CONNECTION_STRING: applicationinsights-connection-string
  image:
    repository: pagopaucommonacr.azurecr.io/pagopaecommercepaymentmethodsservice
    tag: "0.5.0"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuuat.ecommerce.internal.uat.platform.pagopa.it"
    path: /pagopa-ecommerce-payment-methods-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  autoscaling:
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  envConfig:
    MONGO_HOST: pagopa-u-weu-ecommerce-cosmos-account.mongo.cosmos.azure.com
    MONGO_USERNAME: pagopa-u-weu-ecommerce-cosmos-account
    MONGO_PORT: "10255"
    MONGO_SSL_ENABLED: "true"
    AFM_URI: "https://api.dev.platform.pagopa.it/afm/calculator-service/v1/fees"
    AFM_READ_TIMEOUT: "10000"
    AFM_CONNECTION_TIMEOUT: "10000"
    SPRING_MAX_IN_MEM_SIZE: "16777216"
  envSecret:
    MONGO_PASSWORD: mongo-ecommerce-password
    AFM_KEY: afm-api-key
    APPLICATIONINSIGHTS_CONNECTION_STRING: applicationinsights-connection-string
  keyvault:
    name: "pagopa-u-ecommerce-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity: {}
