microservice-chart:
  namespace: "ecommerce"
  nameOverride: ""
  fullnameOverride: ""
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: bluegreen
    service:
      create: true
    deployment:
      create: true
      image:
        repository: pagopapcommonacr.azurecr.io/pagopaecommercepaymentmethodsservice
        tag: "latest"
        pullPolicy: Always
    envConfig:
      MONGO_HOST: pagopa-p-weu-ecommerce-cosmos-account.mongo.cosmos.azure.com
      MONGO_USERNAME: pagopa-p-weu-ecommerce-cosmos-account
      MONGO_PORT: "10255"
      MONGO_SSL_ENABLED: "true"
      AFM_URI: "https://api.platform.pagopa.it/afm/calculator-service/v1/fees"
      AFM_READ_TIMEOUT: "10000"
      AFM_CONNECTION_TIMEOUT: "10000"
      SPRING_MAX_IN_MEM_SIZE: "16777216"
      ELASTIC_APM_SERVICE_NAME: pagopa-ecommerce-payment-methods-service-blue
      ELASTIC_APM_APPLICATION_PACKAGES: it.pagopa.ecommerce.payment.methods
      ELASTIC_APM_SERVER_URL: http://quickstart-apm-http.elastic-system.svc:8200
      ELASTIC_APM_LOG_SENDING: "false"
      ECS_SERVICE_NAME: pagopa-ecommerce-payment-methods-service-blue
      ECS_SERVICE_ENVIRONMENT: prod
    envSecret:
      MONGO_PASSWORD: mongo-ecommerce-password
      AFM_KEY: afm-api-key
      ELASTIC_APM_SECRET_TOKEN: elastic-apm-secret-token
  image:
    repository: pagopapcommonacr.azurecr.io/pagopaecommercepaymentmethodsservice
    tag: "0.10.4"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuprod.ecommerce.internal.platform.pagopa.it"
    path: /pagopa-ecommerce-payment-methods-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  autoscaling:
    minReplica: 2
    maxReplica: 10
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  envConfig:
    MONGO_HOST: pagopa-p-weu-ecommerce-cosmos-account.mongo.cosmos.azure.com
    MONGO_USERNAME: pagopa-p-weu-ecommerce-cosmos-account
    MONGO_PORT: "10255"
    MONGO_SSL_ENABLED: "true"
    AFM_URI: "https://api.platform.pagopa.it/afm/calculator-service/v1/fees"
    AFM_READ_TIMEOUT: "10000"
    AFM_CONNECTION_TIMEOUT: "10000"
    SPRING_MAX_IN_MEM_SIZE: "16777216"
    ELASTIC_APM_SERVICE_NAME: pagopa-ecommerce-payment-methods-service
    ELASTIC_APM_APPLICATION_PACKAGES: it.pagopa.ecommerce.payment.methods
    ELASTIC_APM_SERVER_URL: http://quickstart-apm-http.elastic-system.svc:8200
    ELASTIC_APM_LOG_SENDING: "false"
    ECS_SERVICE_NAME: pagopa-ecommerce-payment-methods-service
    ECS_SERVICE_ENVIRONMENT: prod
  envSecret:
    MONGO_PASSWORD: mongo-ecommerce-password
    AFM_KEY: afm-api-key
    ELASTIC_APM_SECRET_TOKEN: elastic-apm-secret-token
  keyvault:
    name: "pagopa-p-ecommerce-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity: {}
