microservice-chart:
  namespace: "ecommerce"
  nameOverride: "b-pagopa-ecommerce-payment-methods-service"
  fullnameOverride: "b-pagopaecommercepaymentmethodsservice"
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: bluegreen
    service:
      create: true
    deployment:
      create: true
      image:
        repository: pagopaucommonacr.azurecr.io/pagopaecommercepaymentmethodsservice
        tag: "latest"
        pullPolicy: Always
    envConfig:
      MONGO_HOST: pagopa-u-weu-ecommerce-cosmos-account.mongo.cosmos.azure.com
      MONGO_USERNAME: pagopa-u-weu-ecommerce-cosmos-account
      MONGO_PORT: "10255"
      MONGO_SSL_ENABLED: "true"
      MONGO_MIN_POOL_SIZE: "0"
      MONGO_MAX_POOL_SIZE: "50"
      MONGO_MAX_IDLE_TIMEOUT_MS: "600000"
      MONGO_CONNECTION_TIMEOUT_MS: "2000"
      MONGO_SOCKET_TIMEOUT_MS: "10000"
      MONGO_SERVER_SELECTION_TIMEOUT_MS: "2000"
      MONGO_WAITING_QUEUE_MS: "2000"
      MONGO_HEARTBEAT_FREQUENCY_MS: "5000"
      REDIS_PORT: "6380"
      REDIS_SSL_ENABLED: "true"
      AFM_URI: "https://api.uat.platform.pagopa.it/afm/calculator-service/v1/fees"
      AFM_READ_TIMEOUT: "10000"
      AFM_CONNECTION_TIMEOUT: "10000"
      SPRING_MAX_IN_MEM_SIZE: "16777216"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-ecommerce-payment-methods-service-blue,deployment.environment=uat"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
      OTEL_LOGS_EXPORTER: none
      OTEL_TRACES_SAMPLER: "always_on"
      ECS_SERVICE_NAME: pagopa-ecommerce-payment-methods-service-blue
      ECS_SERVICE_ENVIRONMENT: uat
      NPG_URI: "https://stg-ta.nexigroup.com/api/phoenix-0.0"
      NPG_READ_TIMEOUT: "10000"
      NPG_CONNECTION_TIMEOUT: "10000"
      SESSION_URL_BASEPATH: "https://uat.checkout.pagopa.it"
      SESSION_URL_OUTCOME_SUFFIX: "/esito"
      SESSION_URL_CANCEL_SUFFIX: "/esito"
      SESSION_URL_NOTIFICATION_URL: "https://api.uat.platform.pagopa.it/ecommerce/npg/notifications/v1/sessions/{orderId}/outcomes?sessionToken={sessionToken}"
      NPG_SESSIONS_TTL: "900"
      NPG_NOTIFICATION_JWT_VALIDITY_TIME: "900"
      NPG_SO_KEEPALIVE: "true"
      NPG_TCP_KEEPIDLE: "5"
      NPG_TCP_KEEPINTVL: "2"
      NPG_TCP_KEEPCNT: "10"
    envSecret:
      MONGO_PASSWORD: mongo-ecommerce-password
      REDIS_PASSWORD: redis-ecommerce-access-key
      REDIS_HOST: redis-ecommerce-hostname
      AFM_KEY: afm-api-key
      OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
      NPG_API_KEY: npg-api-key
      NPG_NOTIFICATION_JWT_SECRET: npg-notification-signing-key
  image:
    repository: pagopaucommonacr.azurecr.io/pagopaecommercepaymentmethodsservice
    tag: "1.12.0"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 80
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 80
    failureThreshold: 6
    periodSeconds: 10
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuuat.ecommerce.internal.uat.platform.pagopa.it"
    path: /beta/pagopa-ecommerce-payment-methods-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  autoscaling:
    enable: true
    minReplica: 3
    maxReplica: 10
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  terminationGracePeriodSeconds: 30
  deployment:
    create: true
    replicas: 3
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: "100%"
      maxUnavailable: "100%"
  envConfig:
    MONGO_HOST: pagopa-u-weu-ecommerce-cosmos-account.mongo.cosmos.azure.com
    MONGO_USERNAME: pagopa-u-weu-ecommerce-cosmos-account
    MONGO_PORT: "10255"
    MONGO_SSL_ENABLED: "true"
    MONGO_MIN_POOL_SIZE: "0"
    MONGO_MAX_POOL_SIZE: "50"
    MONGO_MAX_IDLE_TIMEOUT_MS: "600000"
    MONGO_CONNECTION_TIMEOUT_MS: "2000"
    MONGO_SOCKET_TIMEOUT_MS: "10000"
    MONGO_SERVER_SELECTION_TIMEOUT_MS: "2000"
    MONGO_WAITING_QUEUE_MS: "2000"
    MONGO_HEARTBEAT_FREQUENCY_MS: "5000"
    REDIS_PORT: "6380"
    REDIS_SSL_ENABLED: "true"
    AFM_URI: "https://api.uat.platform.pagopa.it/ecommerce/mock/gec/v1/fees"
    AFM_URI_V2: "https://api.uat.platform.pagopa.it/ecommerce/mock/gec/v2/fees"
    AFM_READ_TIMEOUT: "10000"
    AFM_CONNECTION_TIMEOUT: "10000"
    SPRING_MAX_IN_MEM_SIZE: "16777216"
    OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-ecommerce-payment-methods-service-blue,deployment.environment=uat"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    ECS_SERVICE_NAME: pagopa-ecommerce-payment-methods-service-blue
    ECS_SERVICE_ENVIRONMENT: uat
    NPG_URI: "https://api.uat.platform.pagopa.it/ecommerce/mock/npg/v1"
    NPG_READ_TIMEOUT: "10000"
    NPG_CONNECTION_TIMEOUT: "10000"
    SESSION_URL_BASEPATH: "https://uat.checkout.pagopa.it"
    SESSION_URL_OUTCOME_SUFFIX: "/esito"
    SESSION_URL_CANCEL_SUFFIX: "/esito"
    SESSION_URL_NOTIFICATION_URL: "https://api.uat.platform.pagopa.it/ecommerce/npg/notifications/v1/sessions/{orderId}/outcomes?sessionToken={sessionToken}"
    NPG_SESSIONS_TTL: "900"
    NPG_NOTIFICATION_JWT_VALIDITY_TIME: "900"
    SERVICE_LOGGING_LEVEL: "info"
    ROOT_LOGGING_LEVEL: "info"
    WARMUP_PAYMENT_METHOD_ID: "378d0b4f-8b69-46b0-8215-07785fe1aad4"
    NPG_SO_KEEPALIVE: "true"
    NPG_TCP_KEEPIDLE: "5"
    NPG_TCP_KEEPINTVL: "2"
    NPG_TCP_KEEPCNT: "10"
  envSecret:
    MONGO_PASSWORD: mongo-ecommerce-password
    REDIS_PASSWORD: redis-ecommerce-access-key
    REDIS_HOST: redis-ecommerce-hostname
    AFM_KEY: ecommerce-load-test-subscription-key
    OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
    NPG_API_KEY: npg-api-key
    NPG_NOTIFICATION_JWT_SECRET: npg-notification-signing-key
  keyvault:
    name: "pagopa-u-ecommerce-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
